### ISSUE TITLE
Synapse server does not start

### ISSUE THREAD

**Issue by ViSTiE** [runcitadel/citadel#10]
Hello,

I have a problem with the Synapse server. I installed it from the App store, but I can't start it. This is how it looks in my App menu:

![image](https://user-images.githubusercontent.com/25864484/180177800-b43aaa0f-a368-44f4-bc9d-64caf8365124.png)

After clicking the icon, it opens a new tab, but the result is always the same:

![image](https://user-images.githubusercontent.com/25864484/180178927-f3f65259-57b6-4b06-ae97-d4e41edca4c6.png)

I tried with IP:Port, citadel.local:Port, but no luck. Can you help me solve this issue?

I appreciate it :)

**Comment by AaronDewes** [comment]
Hi! Sorry to hear about this, can you share the logs from Settings > Troubleshooting?

**Comment by pwltr** [comment]
@AaronDewes Apparently the bot keeps reverting a fix of yours: [6f28fabe853e4260ac3423e438898a153006d4fd](https://github.com/runcitadel/apps/commit/6f28fabe853e4260ac3423e438898a153006d4fd)

**Comment by ViSTiE** [comment]
Hey guys, thank you for fixing it. Is the fix rolled out with the next version? Do I need to update myself or is it done automatically?

**Comment by pwltr** [comment]
@ViSTiE 
The fix is not rolled out to stable yet, I'll close this issue again when it is. To update go to your apps and click "Update".

![Screenshot_20220725_133517](https://user-images.githubusercontent.com/8538369/180768877-a72ccb1e-5cec-4655-a17f-bcc7bed23d11.png)
