### ISSUE TITLE
Lightning Sync Loop

### ISSUE THREAD

**Issue by ghost** [runcitadel/citadel#20]
### Describe the bug

Never-ending sync on Lighting Wallet and Bitcoin Wallet

Bitcoin Core fully synced and running after 1 week.  Lightning Wallet/Bitcoin wallet syncing for over a month

Apologies if this project is dead and I am posting to a zombie group

### Reproduce

Failed merge from Umbrel so had to install from scratch and recover from seed.

-Downloaded old ver of citadel from runcitadel.space (.5), 
-Successful install and citadel found update 0.1.0
-Bitcoin core fully syncd, lightning on a never ending sync.

### Citadel version

0.1.0

### Operating system

Citadel OS/Raspberry Pi

**Comment by AaronDewes** [comment]
Hi! Citael is still in active development, and will hopefully stay in development for many years.

I assume you mean Citadel 0.0.10, because 0.1.0 has not been released yet.

Can you share the log files from Settings > Troubleshooting with me?

**Comment by Opieight** [comment]
Hi Aaron,
Good to hear that the project is still active!  Appreciate you reaching out!  Obviously new to GitHub, hopefully the log attached properly.  
Let me know if there is anything else I can do to help!
[citadel-1666547441741-debug.log](https://github.com/runcitadel/citadel/files/9847185/citadel-1666547441741-debug.log)

**Comment by ghost** [comment]
Moved on from "Citadel", Easy fix!

Appreciate the support!
