### ISSUE TITLE
After upgrade from umbrel no apps in appstore

### ISSUE THREAD

**Issue by buerzel** [runcitadel/citadel#3]
Hi,

thank you very much for your work.
I upgraded to citadel and all looks good.
I used a pihole als docker in umbrel und it working after upgrade.
But in the appstore no apps are shown.
I thought umbrel and the third party apps are in citadel, too.
Is it right?
Thank you.

best wishes

**Comment by AaronDewes** [comment]
Yes, all apps are in Citadel too. The app store being empty is a bug we'll fix soon.

**Comment by AaronDewes** [comment]
Please try updating again, it should work now.

**Comment by buerzel** [comment]
sorry, about the wubUI or direct via docker?

**Comment by AaronDewes** [comment]
Neither, like when you first upgraded to Citadel.

**Comment by buerzel** [comment]
Thank You so much. :-D
Now its working and i see the appstore and the installed apps.

PERFECT Work.
