### ISSUE TITLE
Testnet mode doesn’t seem to be working

### ISSUE THREAD

**Issue by nolim1t** [runcitadel/citadel#4]
Would like to run citadel in testnet to test the waters so to speak.

Any tips on getting testnet mode working?

Usual method doesn't seem to work

**Comment by pwltr** [comment]
If you are using [citadel-dev](https://github.com/runcitadel/citadel-dev) you can now add a network argument with `citadel-dev boot --network testnet` when spinning up a fresh VM. We'll look into a method for easy network switching in the future.

**Comment by pwltr** [comment]
Starting next release you can also use `citadel set network <network>` within a running instance.
