### ISSUE TITLE
"Error: Invalid URL host" when connecting to Zeus

### ISSUE THREAD

**Issue by trevthom** [runcitadel/citadel#5]
Double-checked manual values when connecting to Zeus, but still getting the error.

**Comment by AaronDewes** [comment]
What version of Citadel are you using?

**Comment by trevthom** [comment]
0.5.18

**Comment by AaronDewes** [comment]
I'll try myself later, sorry about the issue

**Comment by trevthom** [comment]
No worries. I'm just here to beta test and play around until more stable. This will likely be my node software of choice as kinks are worked out
