### ISSUE TITLE
Updating breaks citadel

### ISSUE THREAD

**Issue by KushGene** [runcitadel/citadel#9]
Hello, I got a message that v0.0.6 is out so I want to update. Sadly, It took hours in "Stopping Old Containers" and now (new day) I dont even get to my citadel (ERR_CONNECTION_REFUSED).

In my time having a node (not 100% yet) I had to reinstall citadel OS more than 3 times (started from 0.0.4 ) cuz Update never worked.

**Comment by AaronDewes** [comment]
Can you please try to open a terminal or PowerShell on your computer and enter `ssh citadel@citadel`?

When it asks for a password, try `freedom` or your Citadel password.

Then, run `sudo rm -rf ~/citadel/statuses/update-in-progress && sudo ~/citadel/scripts/update/update --repo runcitadel/core#stable`

That should hopefully update your node to 0.0.6 and fix future update issues.

**Comment by KushGene** [comment]
Thank you. A member of another discord server send me this too ^^
On SSH it seems to be working now (containers are stopping and starting).

Citadel is now updated. Thank you very much.

My old method was to re-flash updated OS Version every time ^^
